### ISSUE TITLE
Infinite loading screen.

### ISSUE THREAD

**Issue by 000Dante000** [7erra/VASS-Virtual-Arsenal-Shop-System#26]
I keep getting infinite loading screen whenever im opening the shop menu

**Comment by 7erra** [comment]
There was a bug in one of the scripts which has been fixed with commit 2edfe7b01402f507fc85c9f9ad66333e8821de42. When an error occurs while the arsenal is loading the loading screen will stay because the command to end it is never called. Really annoying but not really influencable by me. All I can and should do is fix all errors which occur.
If the problem persists can you upload your mission folder as a zip file? I will take a look.

**Comment by 000Dante000** [comment]
The issue happened with multiple mission files but i used the mission
example you uploaded and it told me that the mod wasn't loaded even though
it was so i think that might be the issue.

**Comment by 7erra** [comment]
I forgot to remove a "!" from my debugging session. The message should now show up properly. The loading screen bug shouldn't be fixed by that though as it is not dependent on this script?

**Comment by 000Dante000** [comment]
The issue has been fixed. Thanks!

Looking forward for a mission example with a woking cash earning system

**Comment by 000Dante000** [comment]
Im not sure if my messege got sent but im reconfirming it.
The issue has been fixed.

Also is it posible that i could send you a mission file that you can adjust
for mods.? it seems some mods are disabling the money gain script but we
don't know how to fix it

**Comment by 7erra** [comment]
Yeah you can upload your mission file as a zip file and attach it to a new issue. Add the list of mods to the description. I am going to close this one as it has been fixed.
